### ISSUE TITLE
Anonymous functions are not being parsed correctly

### ISSUE THREAD

**Issue by tzilist** [lumpy-turnips/minty#52]
minty.wrap(function (){}) and any variation throws am esprima error

**Comment by tzilist** [comment]
Current work around is to make sure all named functions are working.

**Comment by gcwelborn** [comment]
@tzilist in some ways it's kindof a feature. As far as I know it's best-practice to avoid anonymous functions to help debug stack-traces. Maybe just make it super clear in the readme and highlight the benefits.

**Comment by angieyeh** [comment]
Hey Cruz, thanks for the feedback.

We want to allow users to wrap middleware functions. Even though they are
named (ex. Usercontroller.getUser), when we pass in something
like usercontroller.getuser to minty.wrap, esprima sees it as an anonymous
function so it throws an error. So that is something we will need to
handle.

On Sunday, April 10, 2016, Cruz Welborn <notifications@github.com> wrote:

> @tzilist <https://github.com/tzilist> in some ways it's kindof a feature.
> As far as I know it's best-practice to avoid anonymous functions to help
> debug stack-traces. Maybe just make it super clear in the readme and
> highlight the benefits.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lumpy-turnips/minty/issues/52#issuecomment-208162938>
>


-- 
Sincerely,
Angie Yeh
University of Southern California | Marshall School of Business
Class of 2014 | Business Administration, B.S.
Cell: (626) 497-1991 | angieyeh24@gmail.com

**Comment by tzilist** [comment]
@gcwelborn, that is certainly a possibility, however, my thought here is lot's of people use anonymous functions when defining methods. You're right in that it should be defined but my guess is a lot of people still do it (hence the crisis at Netflix a few months ago). My guess is it would be better for us to support a wider range of styles (even if they aren't best practice).

**Comment by tzilist** [comment]
We have implemented a function to handle these situations. Anonymous functions can now be passed through minty.wrap properly.
